# Importing Libraries

In [1]:
import pandas as pd  #important for Data Analysis
import numpy as np   #For splitting training and test data
import nltk          #for all text processing in nlp
from nltk.corpus import stopwords #for removing stopwords from a sentense like the ,it he, she (those not imp for Classification)
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer  #do lemmatization because it is way more efficient then stemming
import re
from sklearn.model_selection import train_test_split #for traing and testing splitting

# Reading the dataset

In [2]:
dataset = pd.read_csv("Sentiment.csv")  #To read dataset

In [3]:
dataset

id               candidate  candidate_confidence relevant_yn  \
0          1  No candidate mentioned                1.0000         yes   
1          2            Scott Walker                1.0000         yes   
2          3  No candidate mentioned                1.0000         yes   
3          4  No candidate mentioned                1.0000         yes   
4          5            Donald Trump                1.0000         yes   
...      ...                     ...                   ...         ...   
13866  13867  No candidate mentioned                1.0000         yes   
13867  13868           Mike Huckabee                0.9611         yes   
13868  13869                Ted Cruz                1.0000         yes   
13869  13870            Donald Trump                1.0000         yes   
13870  13871                Ted Cruz                0.9242         yes   

       relevant_yn_confidence sentiment  sentiment_confidence  \
0                      1.0000   Neutral                0.6578   
1                      1.0000  Positive                0.6333   
2                      1.0000   Neutral                0.6629   
3                      1.0000  Positive                1.0000   
4                      1.0000  Positive                0.7045   
...                       ...       ...                   ...   
13866                  1.0000  Negative                0.7991   
13867                  1.0000  Positive                0.7302   
13868                  1.0000  Positive                0.8051   
13869                  1.0000  Negative                1.0000   
13870                  0.9614  Positive                0.9614   

                             subject_matter  subject_matter_confidence  \
0                         None of the above                     1.0000   
1                         None of the above                     1.0000   
2                         None of the above                     0.6629   
3                         None of the above                     0.7039   
4                         None of the above                     1.0000   
...                                     ...                        ...   
13866                              Abortion                     0.6014   
13867                     None of the above                     0.9229   
13868                     None of the above                     0.9647   
13869  Women's Issues (not abortion though)                     0.9202   
13870                     None of the above                     0.9242   

               candidate_gold  ... relevant_yn_gold retweet_count  \
0                         NaN  ...              NaN             5   
1                         NaN  ...              NaN            26   
2                         NaN  ...              NaN            27   
3                         NaN  ...              NaN           138   
4                         NaN  ...              NaN           156   
...                       ...  ...              ...           ...   
13866  No candidate mentioned  ...              yes             7   
13867           Mike Huckabee  ...              yes             1   
13868                Ted Cruz  ...              yes            67   
13869            Donald Trump  ...              yes           149   
13870                Ted Cruz  ...              yes            65   

          sentiment_gold                             subject_matter_gold  \
0                    NaN                                             NaN   
1                    NaN                                             NaN   
2                    NaN                                             NaN   
3                    NaN                                             NaN   
4                    NaN                                             NaN   
...                  ...                                             ...   
13866           Negative  Abortion\nWomen's Issues (not abortion though)   
13867         

Not all are inportant one with text and sentiment is important for us 
so we will keep only those things in my data set

In [4]:
dataset = dataset[['text','sentiment']]

In [5]:
dataset

text sentiment
0      RT @NancyLeeGrahn: How did everyone feel about...   Neutral
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
2      RT @TJMShow: No mention of Tamir Rice and the ...   Neutral
3      RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
...                                                  ...       ...
13866  RT @cappy_yarbrough: Love to see men who will ...  Negative
13867  RT @georgehenryw: Who thought Huckabee exceede...  Positive
13868  RT @Lrihendry: #TedCruz As President, I will a...  Positive
13869  RT @JRehling: #GOPDebate Donald Trump says tha...  Negative
13870  RT @Lrihendry: #TedCruz headed into the Presid...  Positive

[13871 rows x 2 columns]

We can take tweets that are +ve,neutal and -ve 
but here i am doing only binary classifiaction (0 & 1) so i am taking only 
positive and negative one .

In [6]:
dataset= dataset[dataset['sentiment']!='Neutral']

In [7]:
dataset

text sentiment
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
3      RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
5      RT @GregAbbott_TX: @TedCruz: "On my first day ...  Positive
6      RT @warriorwoman91: I liked her and was happy ...  Negative
...                                                  ...       ...
13866  RT @cappy_yarbrough: Love to see men who will ...  Negative
13867  RT @georgehenryw: Who thought Huckabee exceede...  Positive
13868  RT @Lrihendry: #TedCruz As President, I will a...  Positive
13869  RT @JRehling: #GOPDebate Donald Trump says tha...  Negative
13870  RT @Lrihendry: #TedCruz headed into the Presid...  Positive

[10729 rows x 2 columns]

# Data Preprocessing

First of all we will split this data in training and test

In [8]:
train,test= train_test_split(dataset,test_size=0.1)   #function 0.1 means we are taking 10% for testing 

In [9]:
train

text sentiment
468    RT @LittleLadyCassy: #GOPDebate Loving Fiorina...  Positive
10331  RT @Lrihendry: #TedCruz headed into the Presid...  Positive
11606  #kasich just admitted having attended a same s...  Negative
905    Maybe tweeting is just not your game. I know! ...  Negative
13767  RT @RWSurferGirl: I am wondering what Fox is u...  Negative
...                                                  ...       ...
9681   You would do well to study the lamestream medi...  Negative
11317  Dear fox news moderator, you forgot to say chi...  Negative
5185   @RealBenCarson congrats on crossing 2 million ...  Positive
2875   RT @hipsterocracy: If I wanted to watch this m...  Negative
9810   I like him for that slam #Trump #GOPDebates ht...  Positive

[9656 rows x 2 columns]

In [10]:
test

text sentiment
10933  RT @RWSurferGirl: Is it just me or does anyone...  Negative
12086  Rubio doesn't understand that there is a Bill ...  Negative
6684   Neither moderator’s in yest’s #GOPDebate expli...  Negative
9072   RT @ericstonestreet: Trump has Cam hands. #GOP...  Negative
3776   RT @AfricanaCarr: Today is the 50th anniversar...  Negative
...                                                  ...       ...
12389  “@RWSurferGirl: Fox News is obviously trying t...  Negative
2544   RT @RedStateJake: Sorry, but @JebBush was as i...  Negative
9141   RT @RWSurferGirl: We the American people pick ...  Negative
2465   RT @buffalopundit: Actually, BUSH'S BROTHER CU...  Negative
4326   10 million people watched FOX #GOPdebate last ...  Negative

[1073 rows x 2 columns]

In [11]:
# lets see a struction of sentence, what to remove and what to process.
train['text'][9720]

'RT @RWSurferGirl: It is very disappointing that Fox News is not conducting a "Fair &amp; Balanced" Debate. 🇺🇸 #GOPDebate  #GOPDebates'

We have to remove all the rt@.... , all hastags (#) - for this we have imported regix
->Now we will make a pattern that is we will develop a regix

In [12]:
pattern = "(#\w+)|(RT\s@\w+:)|(http.*)|(@\w+)"  #regix is complete

Now , we will import constructor of Lemmatizer and Stemming

In [13]:
#for stemming

ps = PorterStemmer()

#for lemmatizer

lemmatizer = WordNetLemmatizer()

In [14]:
def Clean_text(data):
    tweets = [] #array of tweets
    sentiments = [] #array of corrosponding Sentiments
    for index,row in data.iterrows():
        sentence = re.sub(pattern,'',row.text)    # ('pattern',to_replace,in what)
        words = [e.lower() for e in sentence.split()] # making all words lower case , we are splitting in space
        words = [lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')] # lemmatization
        words = ' '.join(words)# now joining word in form of sentence
        tweets.append(words)
        sentiments.append(row.sentiment)
    return tweets,sentiments
        

Let's try this by passing training data

In [15]:
train_tweets,train_sentiments = Clean_text(train)

In [16]:
train_tweets  # we can stopwords , # , @ words are removed

['loving fiorina. smart point!',
 'headed presidential debates. go ted!!',
 "admitted attended sex wedding. that's sound shot nomination circling drain.",
 "maybe tweeting game. know! let's spelling contest ..u win",
 'wondering fox debate -- get rid trump, paul, cruz, carson? 🇺🇸',
 'hey , bigger talking point last night? make think whole debate sham.',
 'fan deserves better called bimbo job',
 "i've never huge christie fan, he's made point mention entitlement reform. one.",
 "/trump ignorant. presidential. class money. clearly money can't buy u class &amp; skipped dignity too.",
 'trump cam hands.',
 ': "on first day rescind every illegal executive action taken barack obama."',
 'trump: ‘i would’ shut gov’t defund planned parenthood obamacare',
 'cruz refers terrible "obama-clinton foreign policy" past 6 years. kerry so since 2/13.',
 'let someone else handle future debates. incompetent.',
 'rubio-backed insurance market "covers 80 people" -obamacare cover 1.6m fl alone',
 'need antac

Now lets make data_frame so that it becomeeasy for us to process

In [17]:
final_data = {'tweets':train_tweets,'sentiments':train_sentiments} #This is our Dictionary

In [18]:
#construct a data frame
processed_data = pd.DataFrame(final_data)

In [19]:
processed_data

tweets sentiments
0                          loving fiorina. smart point!   Positive
1                 headed presidential debates. go ted!!   Positive
2     admitted attended sex wedding. that's sound sh...   Negative
3     maybe tweeting game. know! let's spelling cont...   Negative
4     wondering fox debate -- get rid trump, paul, c...   Negative
...                                                 ...        ...
9651  would well study lamestream media's interpreta...   Negative
9652  dear fox news moderator, forgot say chinese ha...   Negative
9653               congrats crossing 2 million like fb!   Positive
9654  wanted watch many white men hate woman talk i'...   Negative
9655                                          like slam   Positive

[9656 rows x 2 columns]

We will now encode the Sentiments

In [20]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
processed_data['sentiments'] = labelencoder.fit_transform(processed_data['sentiments'])

In [21]:
processed_data

tweets  sentiments
0                          loving fiorina. smart point!           1
1                 headed presidential debates. go ted!!           1
2     admitted attended sex wedding. that's sound sh...           0
3     maybe tweeting game. know! let's spelling cont...           0
4     wondering fox debate -- get rid trump, paul, c...           0
...                                                 ...         ...
9651  would well study lamestream media's interpreta...           0
9652  dear fox news moderator, forgot say chinese ha...           0
9653               congrats crossing 2 million like fb!           1
9654  wanted watch many white men hate woman talk i'...           0
9655                                          like slam           1

[9656 rows x 2 columns]

If returning 0 -> 'Negative' , 
If returning 1 -> 'Positive'

# Converting Words into vector

In [22]:
from sklearn.feature_extraction.text import CountVectorizer #tfid can increase accuracy
cv= CountVectorizer(ngram_range=(1,3))      # If a sentence has 6 word it will make vector of maximum 3 words
cv.fit(processed_data['tweets'])        # As we have to fir count vectorin tweets colums

CountVectorizer(ngram_range=(1, 3))

In [23]:
x_train = cv.transform(processed_data['tweets'])   # Saving transformed processed data in x_train

In [24]:
print(x_train.shape)   # every word is made vector thats why we have more column = 82036

(9656, 82204)


In [25]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

now we have independent columns , we have now dependent columns of only sentiments 
therefore,

In [26]:
target = processed_data['sentiments'].values

In [27]:
target

array([1, 1, 0, ..., 1, 0, 1])

#Target is saved in the form of numpy array

# Sentiment Analysis (Model Building)

Now we have to use different models like logistic regression or Naive Bayes or Random forest or different boosting technique 

We will use Naive Bayes here

In [28]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()               #Calling constructor ,it has been initialized

In [29]:
classifier.fit(x_train.toarray(),target)  #to array so that proper array goes not its instance

MultinomialNB()

Have have runned and fitted the classifier now twe have to predict

In [30]:
test

text sentiment
10933  RT @RWSurferGirl: Is it just me or does anyone...  Negative
12086  Rubio doesn't understand that there is a Bill ...  Negative
6684   Neither moderator’s in yest’s #GOPDebate expli...  Negative
9072   RT @ericstonestreet: Trump has Cam hands. #GOP...  Negative
3776   RT @AfricanaCarr: Today is the 50th anniversar...  Negative
...                                                  ...       ...
12389  “@RWSurferGirl: Fox News is obviously trying t...  Negative
2544   RT @RedStateJake: Sorry, but @JebBush was as i...  Negative
9141   RT @RWSurferGirl: We the American people pick ...  Negative
2465   RT @buffalopundit: Actually, BUSH'S BROTHER CU...  Negative
4326   10 million people watched FOX #GOPdebate last ...  Negative

[1073 rows x 2 columns]

In [31]:
test_tweets,test_sentiments = Clean_text(test)

In [32]:
test_tweets

['anyone else want punch chris wallace face? 🇺🇸',
 'rubio understand bill right',
 "neither moderator’s yest’s explicitly ref'd mvmnt,no candidate ack.it",
 'trump cam hands.',
 "today 50th anniversary one question tonight's . message received, lo…",
 'fire comment woman @ weigh',
 'world leader said "put bomb away, guy destroy america themselves."',
 'american people pick next president united state fox news 🇺🇸',
 'senator cruz, word god? spit tequila. damn megyn kelly, expensive kind.',
 'scott walker brought harley reason president.',
 'unplanned parenthood.',
 "hopefully we'll find god stand taxing-pimps issue.",
 "takeaway they're terrible, hate tell that's whole night life never get back.",
 "hey ! absolutely fearful ? i'm lol refuse ask questions! …",
 "used crazy&gt; stir pot, that's unprofessional!",
 'really need make largest military power world bigger?',
 ". shared inspiring applause line last night's :",
 'wow. primary source entertainment next six month cemented.',
 'fox 

it is cleaned now,
noe we will make dictionary and then make it a data frame

In [33]:
data_test = {'tweets':test_tweets,'sentiments':test_sentiments}
final_test_data = pd.DataFrame(data_test)

In [34]:
final_test_data

tweets sentiments
0         anyone else want punch chris wallace face? 🇺🇸   Negative
1                           rubio understand bill right   Negative
2     neither moderator’s yest’s explicitly ref'd mv...   Negative
3                                      trump cam hands.   Negative
4     today 50th anniversary one question tonight's ...   Negative
...                                                 ...        ...
1068  “: fox news obviously trying influence makeup ...   Negative
1069                  sorry, inspiring manila envelope.   Negative
1070  american people pick next president united sta...   Negative
1071      actually, bush's brother cut deal leave iraq.   Negative
1072  10 million people watched fox last nite &amp; ...   Negative

[1073 rows x 2 columns]

We have got Processed Data

In [35]:
x_test = cv.transform(final_test_data['tweets'])

In [36]:
x_test          #instance of s.. matrix

<1073x82204 sparse matrix of type '<class 'numpy.int64'>'
	with 15173 stored elements in Compressed Sparse Row format>

In [37]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
x_test.shape     # 82036 shold be exactly same as of training

(1073, 82204)

In [39]:
y_pred = classifier.predict(x_test.toarray())

In [40]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

We want to check Acccuracy of  Naive Bayes Model

In [41]:
final_test_data['sentiments'] = labelencoder.fit_transform(final_test_data['sentiments'])

In [42]:
final_test_data

tweets  sentiments
0         anyone else want punch chris wallace face? 🇺🇸           0
1                           rubio understand bill right           0
2     neither moderator’s yest’s explicitly ref'd mv...           0
3                                      trump cam hands.           0
4     today 50th anniversary one question tonight's ...           0
...                                                 ...         ...
1068  “: fox news obviously trying influence makeup ...           0
1069                  sorry, inspiring manila envelope.           0
1070  american people pick next president united sta...           0
1071      actually, bush's brother cut deal leave iraq.           0
1072  10 million people watched fox last nite &amp; ...           0

[1073 rows x 2 columns]

In [43]:
actual_values = final_test_data['sentiments'].values

In [44]:
actual_values    #Now we get actual values in the form of numpy array

array([0, 0, 0, ..., 0, 0, 0])

In [45]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,actual_values)) 
# we have to encode test_sentiments

0.8490214352283317


84% is good Accuracy

Now our Model is built

In [46]:
final_test_data

tweets  sentiments
0         anyone else want punch chris wallace face? 🇺🇸           0
1                           rubio understand bill right           0
2     neither moderator’s yest’s explicitly ref'd mv...           0
3                                      trump cam hands.           0
4     today 50th anniversary one question tonight's ...           0
...                                                 ...         ...
1068  “: fox news obviously trying influence makeup ...           0
1069                  sorry, inspiring manila envelope.           0
1070  american people pick next president united sta...           0
1071      actually, bush's brother cut deal leave iraq.           0
1072  10 million people watched fox last nite &amp; ...           0

[1073 rows x 2 columns]

In [47]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

row 1 i.e., [0, 0, 0, ..., 0, 0, 0] corrosponds to - jeb bush reminds elevator music. hear listen. 🇺🇸

In [48]:
x_test.toarray()[0]   #row 1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

lets see what model provide us it's actual sentiment is 0 that is -ve

In [49]:
classifier.predict(x_test.toarray()[[0]])   #for trainig we have to provide matrix independent colum->matrix & dependent cloumn->vector

array([0])

we have got prodictor of 0 means its a negative sentiment